<a href="https://colab.research.google.com/github/jubair0614/LLMScratch/blob/main/pytorch_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
print(torch.__version__)

2.11.0+cu128


In [ ]:
print(torch.cuda.is_available())

True


In [ ]:
import numpy as np
a = torch.tensor([1, 2, 4])
b = torch.tensor([[2, 3], [5, 4]])
print(a.shape)
print(b)
print(b.transpose(1, 0))

arr = np.array([[2, 3, 4], [1, 0, 2]])
b = torch.from_numpy(arr)
print(arr)
print(torch.from_numpy(arr))

print(a.dtype)
print(b.view(3, 2))
print(b.reshape(3 ,2))
print(b.T)
print(b.matmul(b.T))
print(b @ b.T)

torch.Size([3])
tensor([[2, 3],
        [5, 4]])
tensor([[2, 5],
        [3, 4]])
[[2 3 4]
 [1 0 2]]
tensor([[2, 3, 4],
        [1, 0, 2]])
torch.int64
tensor([[2, 3],
        [4, 1],
        [0, 2]])
tensor([[2, 3],
        [4, 1],
        [0, 2]])
tensor([[2, 1],
        [3, 0],
        [4, 2]])
tensor([[29, 10],
        [10,  5]])
tensor([[29, 10],
        [10,  5]])


In [ ]:
import torch.nn.functional as F

y = torch.tensor([1.0])
w1 = torch.tensor([2.2])
x1 = torch.tensor([1.1])
b = torch.tensor([0.0])

z = w1 * x1 + b
a = F.sigmoid(z)
loss = F.binary_cross_entropy(a, y)
print(loss)

tensor(0.0852)


In [ ]:
from torch.nn import functional as F
from torch.autograd import grad

y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2], requires_grad=True)
b = torch.tensor([0.0], requires_grad=True)

z = w1 * x1 + b
a = F.sigmoid(z)
loss = F.binary_cross_entropy(a, y)

grad_L_w1 = grad(loss, w1, retain_graph=True)
grad_L_b = grad(loss, b, retain_graph=True)
print(grad_L_w1)
print(grad_L_b)

(tensor([-0.0898]),)
(tensor([-0.0817]),)


In [ ]:
loss.backward()
print(w1.grad)
print(b.grad)

tensor([-0.0898])
tensor([-0.0817])
